// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgCreateVote } from "./types/daomint/daomint/tx";
import { MsgCreateVoting } from "./types/daomint/daomint/tx";


export { MsgCreateVote, MsgCreateVoting };

type sendMsgCreateVoteParams = {
  value: MsgCreateVote,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreateVotingParams = {
  value: MsgCreateVoting,
  fee?: StdFee,
  memo?: string
};


type msgCreateVoteParams = {
  value: MsgCreateVote,
};

type msgCreateVotingParams = {
  value: MsgCreateVoting,
};


export const registry = new Registry(msgTypes);

const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgCreateVote({ value, fee, memo }: sendMsgCreateVoteParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateVote: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreateVote({ value: MsgCreateVote.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateVote: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreateVoting({ value, fee, memo }: sendMsgCreateVotingParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateVoting: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreateVoting({ value: MsgCreateVoting.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateVoting: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgCreateVote({ value }: msgCreateVoteParams): EncodeObject {
			try {
				return { typeUrl: "/daomint.daomint.MsgCreateVote", value: MsgCreateVote.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateVote: Could not create message: ' + e.message)
			}
		},
		
		msgCreateVoting({ value }: msgCreateVotingParams): EncodeObject {
			try {
				return { typeUrl: "/daomint.daomint.MsgCreateVoting", value: MsgCreateVoting.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateVoting: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			DaomintDaomint: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;